name: Complex Workflow para

on: [push]

jobs:
  just-checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  para1:
    runs-on: ubuntu-latest

    steps:
    - name: syncing some server
      uses: sleep 30

  para2:
    runs-on: ubuntu-latest

    steps:
    - name: syncing another server
      run: sleep 30
